### ISSUE TITLE
[RFC] Use mapped superclasses instead of provide the implemented entities

### ISSUE THREAD

**Issue by phansys** [hackzilla-project/TicketBundle#128]
As suggested before (#51, #63, #110), this issue is open to track the need for providing [mapped superclasses](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/inheritance-mapping.html#mapped-superclasses) instead of implemented entities. The classes that now are part of the `Hackzilla\Bundle\TicketBundle\Entity` namespace could be provided as a base for the model in order to ease their implementation.
This enable this bundle to be used with Doctrine ORM and ODM.

**Comment by hackzilla** [comment]
I'm abandoning using superclasses as there were too many issue with trying to get it working with doctrine relationships.
We are using Symfony maker to help build the entities in v4.
