### ISSUE TITLE
add Symfony 5 Support?

### ISSUE THREAD

**Issue by RootProgger** [hackzilla-project/TicketBundle#157]
is it possible to support Symfony 5?

**Comment by Exellent1988** [comment]
symfony 5.4 has a conflict with the symfony -console version which is 5.3 atm. so i can't install the packadge. is there any progress regarding the 5.x implementation?

**Comment by hackzilla** [comment]
@RootProgger @Exellent1988 I'll have at this.
Is this a project that you are currently using or want to use?

@phansys I'll have a look at see if this is a quick win.

**Comment by phansys** [comment]
IIRC, there was a blocker around Twig and some other packages. But feel free to ping me if you need support with this task :+1:

**Comment by Exellent1988** [comment]
> @RootProgger @Exellent1988 I'll have at this. Is this a project that you are currently using or want to use?
> 
> @phansys I'll have a look at see if this is a quick win.

I'll would love to use the bundle in our project. at least i was looking for a solution which is allready to use, instead of coding it all by myself.

**Comment by hackzilla** [comment]
@phansys I think I've got it working, with the exception of doctrine mapping.
https://github.com/hackzilla-project/TicketBundleDemoApp/tree/v4

The issue I'm facing is with the `mapped-superclass` definition for the associations.
Specifically `inversed-by`.

```
  <mapped-superclass name="Hackzilla\Bundle\TicketBundle\Model\TicketMessageWithAttachment">
   ...
    <many-to-one field="ticket" target-entity="Ticket" inversed-by="messages">
      <join-column name="ticket_id" referenced-column-name="id" />
    </many-to-one>
  </mapped-superclass>
```

With inversed-by  it throws invalid mapping.

```
Mapping
-------

 [FAIL] The entity-class App\Entity\TicketMessageWithAttachment mapping is invalid:
 * The association App\Entity\TicketMessageWithAttachment#ticket refers to the inverse side field Hackzilla\Bundle\TicketBundle\Model\Ticket#messages which does not exist.


 [FAIL] The entity-class Hackzilla\Bundle\TicketBundle\Model\TicketMessageWithAttachment mapping is invalid:
 * The association Hackzilla\Bundle\TicketBundle\Model\TicketMessageWithAttachment#ticket refers to the inverse side field Hackzilla\Bundle\TicketBundle\Model\Ticket#messages which does not exist.
```

Without `inversed-by` it appears to work but you cannot retrieve the ticket messages.

It's seems like it wants the inverse relationship to be setup on the Ticket, like so.

```
<one-to-many field="messages" target-entity="Hackzilla\Bundle\TicketBundle\Model\TicketMessageWithAttachment" mapped-by="ticket" />
```

However, that throws an illegal message.

```
In MappingException.php line 644:
                                                                                                                                                            
  It is illegal to put an inverse side one-to-many or many-to-many association on mapped superclass 'Hackzilla\Bundle\TicketBundle\Model\Ticket#messages'.  
 ```

I am at a loss.

**Comment by hackzilla** [comment]
v4 is close to release now, with Symfony 5 support.
