### ISSUE TITLE
Trouble with PermissionManager and UserManager

### ISSUE THREAD

**Issue by regisgrison** [hackzilla-project/TicketBundle#253]
Hi,

Regarding a crash I had and that commit: https://github.com/hackzilla-project/TicketBundle/commit/595df4cb94d4abe57737da65a0c21a4c2fb26167

I wonder if the `setUserManager()` you added in `UserManagerTrait.php` should not be in `PermissionManagerTrait.php`

Anyway I have a fatal error if I don't add it to mine because of this in `manager.php`:
```
        ->set(PermissionManagerInterface::class)
            ->class('%hackzilla_ticket.manager.permission.class%')
            ->public()
            ->call('setUserManager', [
                new ReferenceConfigurator(UserManagerInterface::class),
            ])```

**Comment by hackzilla** [comment]
The idea of those traits was just to add getters/setters for those particular managers.
`Hackzilla\Bundle\TicketBundle\Manager\PermissionManager` uses `UserManagerTrait`

It looks like I've messed up somewhere, as `src/Manager/PermissionManager.php` differs from my demo implementation `https://github.com/hackzilla-project/TicketBundleDemoApp/blob/v4/src/Manager/TicketPermissionManager.php`.

**Comment by hackzilla** [comment]
I should have looked more carefully at my code yesterday.
TicketPermissionManager.php extends PermissionManager from the bundle.

You just need to add UserManagerTrait to your class.
Maybe I should add the word `Setter` into the trait to make it more clear?

**Comment by regisgrison** [comment]
OK, I just understand that I had to use `UserManagerTrait` in my `PermissionManager`. I'll try it.

In fact I made `xxxManager` use `xxxTrait` and `xxxInterface` without thinking we could use another trait in it.
