### ISSUE TITLE
[Security] Hackzilla\Bundle\TicketBundle\Manager::hasPermission() result is ignored, meaning permissions are not checked and operation is always allowed

### ISSUE THREAD

**Issue by thibaut-decherit** [hackzilla-project/TicketBundle#263]
`Hackzilla\Bundle\TicketBundle\Manager::hasPermission()` returns a boolean, but calls to that function do not attempt to use its result.
They probably call it expecting it will throw an exception if access should not be granted (e.g. [here](https://github.com/hackzilla-project/TicketBundle/blob/4.x/Controller/TicketController.php#L175)), but it won't because said exception is caught and [the function returns false instead](https://github.com/hackzilla-project/TicketBundle/blob/4.x/Manager/UserManager.php#L99=).

**Comment by hackzilla** [comment]
Thank you, I'm not entirely sure how this passed me by.
