### ISSUE TITLE
Error when filling the entity part 4.x

### ISSUE THREAD

**Issue by developingjan** [hackzilla-project/TicketBundle#290]
Hello everyone!

I'm using the version 4.x version with Symfony 5, and php 8.1.

When I try to do the entity part i get this error:

$ php bin/console make:entity:ticket

In AbstractMaker.php line 277:
                                                                                                                                 
 Attempted to call an undefined method named "isClassAnnotated" of class "Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper".  

Anyone knows why?

Thank you

**Comment by hackzilla** [comment]
I don't think that the maker bundle was designed with extension in mind.
However, it was the best option open to me with creating the entities for this project.

They removed support for Annotation.
https://github.com/symfony/maker-bundle/commit/e70cc832a1aabfff9cdb3de39262de1987e6e081

I have pushed a commit that checks if the isClassAnnotated method exists.

**Comment by developingjan** [comment]
Hey! Now it's working the command part, and all it seems created, but now I have this issue:


The controller for URI "/panel/ticket/" is not callable: Argument 2 passed to "Hackzilla\Bundle\TicketBundle\Manager\UserManager::__construct()" MUST be an object repository for a class implementing "Hackzilla\Bundle\TicketBundle\Model\UserInterface".

![Captura de pantalla 2023-08-04 a les 13 47 04](https://github.com/hackzilla-project/TicketBundle/assets/18490786/416947c0-6a75-440a-a8cd-b4a987311d56)

**Comment by developingjan** [comment]
Okay, after checking the Entity part, I've seen that the bundle custom interface with each getter/setter was missing.
Now working!

[https://github.com/hackzilla-project/TicketBundle/blob/master/Resources/doc/setup/feature/events.md](url)

also, it's good to check the demo files if someone has the same issue in the future
[https://github.com/hackzilla-project/TicketBundleDemoApp](url)

sorry for bother you
